import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { eq } from 'drizzle-orm';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { skills, categories, skillPacks, skillPackItems } from './schema';
import { TESTING_TYPES, FRAMEWORKS, LANGUAGES, DOMAINS } from '@qaskills/shared';

/**
 * Read the markdown body (everything after YAML frontmatter) from a seed-skills SKILL.md file.
 * Returns empty string if the file doesn't exist.
 */
function readSkillBody(slug: string): string {
  try {
    const filePath = resolve(__dirname, '../../../../seed-skills', slug, 'SKILL.md');
    const content = readFileSync(filePath, 'utf-8');
    // Strip YAML frontmatter: content between first --- and second ---
    const match = content.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/);
    return match ? match[1].trim() : content;
  } catch {
    return '';
  }
}

async function seed() {
  if (!process.env.DATABASE_URL) {
    console.log('DATABASE_URL not set, skipping seed');
    return;
  }

  const sql = neon(process.env.DATABASE_URL);
  const db = drizzle(sql);

  console.log('Seeding categories...');

  // Seed categories
  const allCategories = [
    ...TESTING_TYPES.map((t) => ({ name: t.name, slug: t.slug, description: t.description, type: 'testingType' as const, icon: t.icon, color: t.color })),
    ...FRAMEWORKS.map((f) => ({ name: f.name, slug: f.slug, description: f.description, type: 'framework' as const, icon: f.icon, color: f.color })),
    ...LANGUAGES.map((l) => ({ name: l.name, slug: l.slug, description: '', type: 'language' as const, icon: l.icon, color: l.color })),
    ...DOMAINS.map((d) => ({ name: d.name, slug: d.slug, description: d.description, type: 'domain' as const, icon: d.icon, color: d.color })),
  ];

  for (const cat of allCategories) {
    await db.insert(categories).values(cat).onConflictDoNothing();
  }

  console.log(`Seeded ${allCategories.length} categories`);

  // Seed skills
  console.log('Seeding skills...');

  const seedSkills = [
    { name: 'Playwright E2E Testing', slug: 'playwright-e2e', description: 'Comprehensive Playwright end-to-end testing patterns with Page Object Model, fixtures, and best practices', authorName: 'thetestingacademy', qualityScore: 92, installCount: 86, weeklyInstalls: 86, testingTypes: ['e2e', 'visual'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true },
    { name: 'Playwright API Testing', slug: 'playwright-api', description: 'API testing with Playwright APIRequestContext for REST and GraphQL endpoints', authorName: 'thetestingacademy', qualityScore: 88, installCount: 32, weeklyInstalls: 32, testingTypes: ['api'], frameworks: ['playwright'], languages: ['typescript'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Cypress E2E Testing', slug: 'cypress-e2e', description: 'Cypress end-to-end testing with custom commands, intercepts, and component testing', authorName: 'thetestingacademy', qualityScore: 90, installCount: 58, weeklyInstalls: 58, testingTypes: ['e2e'], frameworks: ['cypress'], languages: ['javascript', 'typescript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true },
    { name: 'Selenium Java Testing', slug: 'selenium-java', description: 'Selenium WebDriver with Java using Page Object Model and TestNG', authorName: 'thetestingacademy', qualityScore: 85, installCount: 22, weeklyInstalls: 22, testingTypes: ['e2e'], frameworks: ['selenium'], languages: ['java'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'k6 Performance Testing', slug: 'k6-performance', description: 'Modern load testing with k6 including thresholds, scenarios, and custom metrics', authorName: 'thetestingacademy', qualityScore: 87, installCount: 35, weeklyInstalls: 35, testingTypes: ['performance', 'load'], frameworks: ['k6'], languages: ['javascript'], domains: ['api', 'web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true },
    { name: 'JMeter Load Testing', slug: 'jmeter-load', description: 'Apache JMeter load testing with thread groups, assertions, and distributed testing', authorName: 'thetestingacademy', qualityScore: 82, installCount: 15, weeklyInstalls: 15, testingTypes: ['load', 'performance'], frameworks: ['jmeter'], languages: ['java'], domains: ['api', 'web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'OWASP Security Testing', slug: 'owasp-security', description: 'OWASP Top 10 security testing patterns and vulnerability scanning', authorName: 'thetestingacademy', qualityScore: 89, installCount: 26, weeklyInstalls: 26, testingTypes: ['security'], frameworks: [], languages: ['typescript', 'python'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true },
    { name: 'Appium Mobile Testing', slug: 'appium-mobile', description: 'Mobile app testing automation for iOS and Android with Appium', authorName: 'thetestingacademy', qualityScore: 84, installCount: 11, weeklyInstalls: 11, testingTypes: ['mobile', 'e2e'], frameworks: ['appium'], languages: ['java', 'typescript'], domains: ['mobile'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Axe-core Accessibility', slug: 'axe-accessibility', description: 'Automated accessibility testing with axe-core and WCAG 2.1 compliance', authorName: 'thetestingacademy', qualityScore: 86, installCount: 14, weeklyInstalls: 14, testingTypes: ['accessibility'], frameworks: ['axe-core'], languages: ['typescript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Test Data Generation', slug: 'test-data-generation', description: 'Test data strategies using Faker.js, factories, builders, and database seeding', authorName: 'thetestingacademy', qualityScore: 83, installCount: 18, weeklyInstalls: 18, testingTypes: ['unit', 'integration', 'e2e'], frameworks: [], languages: ['typescript', 'python', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'REST Assured API Testing', slug: 'rest-assured-api', description: 'Java REST API testing with REST Assured including JSON schema validation', authorName: 'thetestingacademy', qualityScore: 85, installCount: 13, weeklyInstalls: 13, testingTypes: ['api'], frameworks: ['rest-assured'], languages: ['java'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Jest Unit Testing', slug: 'jest-unit', description: 'Jest unit testing patterns with mocking, spies, snapshots, and async testing', authorName: 'thetestingacademy', qualityScore: 91, installCount: 64, weeklyInstalls: 64, testingTypes: ['unit'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true },
    { name: 'Pytest Patterns', slug: 'pytest-patterns', description: 'Python testing with pytest fixtures, parametrize, markers, and plugins', authorName: 'thetestingacademy', qualityScore: 88, installCount: 41, weeklyInstalls: 41, testingTypes: ['unit', 'integration'], frameworks: ['pytest'], languages: ['python'], domains: ['api', 'web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Postman API Testing', slug: 'postman-api', description: 'Postman collections, environments, pre-request scripts, and Newman CI', authorName: 'thetestingacademy', qualityScore: 84, installCount: 19, weeklyInstalls: 19, testingTypes: ['api'], frameworks: ['postman'], languages: ['javascript'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'BDD/Cucumber Patterns', slug: 'bdd-cucumber', description: 'Behavior-driven development with Cucumber, Gherkin, and step definitions', authorName: 'thetestingacademy', qualityScore: 82, installCount: 9, weeklyInstalls: 9, testingTypes: ['bdd', 'e2e'], frameworks: ['cucumber'], languages: ['typescript', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Test Plan Generation', slug: 'test-plan-generation', description: 'Generate comprehensive test plans with coverage matrices and risk-based testing', authorName: 'thetestingacademy', qualityScore: 80, installCount: 8, weeklyInstalls: 8, testingTypes: ['e2e', 'integration', 'unit'], frameworks: [], languages: ['typescript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Bug Report Writing', slug: 'bug-report-writing', description: 'Write clear bug reports with reproduction steps and severity classification', authorName: 'thetestingacademy', qualityScore: 78, installCount: 6, weeklyInstalls: 6, testingTypes: [], frameworks: [], languages: [], domains: ['web', 'api', 'mobile'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'CI/CD Pipeline Config', slug: 'cicd-pipeline', description: 'Configure testing in CI/CD pipelines for GitHub Actions, Jenkins, and GitLab CI', authorName: 'thetestingacademy', qualityScore: 85, installCount: 28, weeklyInstalls: 28, testingTypes: ['integration'], frameworks: [], languages: ['typescript'], domains: ['devops'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Visual Regression Testing', slug: 'visual-regression', description: 'Visual regression testing with Playwright screenshots and diff comparison', authorName: 'thetestingacademy', qualityScore: 86, installCount: 16, weeklyInstalls: 16, testingTypes: ['visual', 'e2e'], frameworks: ['playwright'], languages: ['typescript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Contract Testing (Pact)', slug: 'contract-testing-pact', description: 'Consumer-driven contract testing with Pact and Pact Broker', authorName: 'thetestingacademy', qualityScore: 84, installCount: 7, weeklyInstalls: 7, testingTypes: ['contract', 'api'], frameworks: ['pact'], languages: ['typescript', 'java'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Vibe Check - Browser Automation', slug: 'vibe-check', description: 'Automate Chrome browser interactions via CLI with persistent daemon mode. Navigate pages, extract content, click elements, type text, manage tabs, and take screenshots.', authorName: 'vibiumdev', qualityScore: 88, installCount: 60, weeklyInstalls: 60, testingTypes: ['e2e', 'visual'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'opencode', 'gemini-cli', 'codex', 'amp'], featured: true, verified: true, githubUrl: 'https://github.com/vibiumdev/vibium' },
    { name: 'Agent Browser', slug: 'agent-browser', description: 'Browser automation tool by Vercel Labs enabling programmatic web interaction. Navigate URLs, capture interactive elements with refs, fill forms, take screenshots, generate PDFs, and run parallel sessions.', authorName: 'vercel-labs', qualityScore: 95, installCount: 47, weeklyInstalls: 47, testingTypes: ['e2e', 'visual', 'accessibility'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web', 'mobile'], agents: ['claude-code', 'cursor', 'github-copilot', 'opencode', 'gemini-cli', 'codex', 'amp', 'windsurf', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true, githubUrl: 'https://github.com/vercel-labs/agent-browser' },
    { name: 'Storybook Component Testing', slug: 'storybook-testing', description: 'Test React, Vue, and Angular components in isolation with Storybook interactions and play functions', authorName: 'thetestingacademy', qualityScore: 87, installCount: 29, weeklyInstalls: 29, testingTypes: ['unit', 'visual'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'WebdriverIO E2E', slug: 'webdriverio-e2e', description: 'Cross-browser E2E testing with WebdriverIO, Cucumber integration, and visual regression', authorName: 'thetestingacademy', qualityScore: 84, installCount: 17, weeklyInstalls: 17, testingTypes: ['e2e', 'visual'], frameworks: ['selenium'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'TestCafe Testing', slug: 'testcafe-testing', description: 'Node.js E2E testing framework with TypeScript support, smart assertions, and parallel execution', authorName: 'thetestingacademy', qualityScore: 82, installCount: 12, weeklyInstalls: 12, testingTypes: ['e2e'], frameworks: ['selenium'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Puppeteer Automation', slug: 'puppeteer-automation', description: 'Headless Chrome automation with Puppeteer for web scraping, PDF generation, and E2E testing', authorName: 'thetestingacademy', qualityScore: 88, installCount: 38, weeklyInstalls: 38, testingTypes: ['e2e', 'browser-automation'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true },
    { name: 'Artillery Load Testing', slug: 'artillery-load', description: 'Modern load testing toolkit with YAML-based scenarios, metrics, and CI/CD integration', authorName: 'thetestingacademy', qualityScore: 83, installCount: 19, weeklyInstalls: 19, testingTypes: ['load', 'performance'], frameworks: ['k6'], languages: ['javascript'], domains: ['api', 'web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Supertest API Testing', slug: 'supertest-api', description: 'HTTP assertion library for Node.js API testing with Express, Koa, and Fastify', authorName: 'thetestingacademy', qualityScore: 86, installCount: 27, weeklyInstalls: 27, testingTypes: ['api', 'integration'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'GraphQL Testing', slug: 'graphql-testing', description: 'GraphQL API testing with schema validation, query testing, and mutation verification', authorName: 'thetestingacademy', qualityScore: 85, installCount: 21, weeklyInstalls: 21, testingTypes: ['api'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Mocha Testing Framework', slug: 'mocha-testing', description: 'Flexible JavaScript testing framework with async support, hooks, and rich reporter ecosystem', authorName: 'thetestingacademy', qualityScore: 81, installCount: 15, weeklyInstalls: 15, testingTypes: ['unit', 'integration'], frameworks: ['jest'], languages: ['javascript', 'typescript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Vitest Unit Testing', slug: 'vitest-testing', description: 'Blazing fast Vite-native unit testing with Jest-compatible API and ESM support', authorName: 'thetestingacademy', qualityScore: 89, installCount: 42, weeklyInstalls: 42, testingTypes: ['unit'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true },
    { name: 'React Testing Library', slug: 'react-testing-library', description: 'User-centric React component testing with queries, events, and async utilities', authorName: 'thetestingacademy', qualityScore: 91, installCount: 53, weeklyInstalls: 53, testingTypes: ['unit', 'integration'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true },
    { name: 'Vue Testing Utils', slug: 'vue-testing-utils', description: 'Official Vue.js testing utilities for component mounting, mocking, and assertions', authorName: 'thetestingacademy', qualityScore: 87, installCount: 31, weeklyInstalls: 31, testingTypes: ['unit'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Angular Testing', slug: 'angular-testing', description: 'Angular TestBed component testing with dependency injection, async testing, and Jasmine', authorName: 'thetestingacademy', qualityScore: 86, installCount: 24, weeklyInstalls: 24, testingTypes: ['unit', 'integration'], frameworks: ['jest'], languages: ['typescript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Detox Mobile Testing', slug: 'detox-mobile', description: 'Gray box E2E testing for React Native apps on iOS and Android simulators', authorName: 'thetestingacademy', qualityScore: 85, installCount: 18, weeklyInstalls: 18, testingTypes: ['mobile', 'e2e'], frameworks: ['appium'], languages: ['javascript', 'typescript'], domains: ['mobile'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'XCUITest iOS Testing', slug: 'xcuitest-ios', description: 'Native iOS UI testing with Swift and Xcode Test Navigator integration', authorName: 'thetestingacademy', qualityScore: 83, installCount: 14, weeklyInstalls: 14, testingTypes: ['mobile', 'e2e'], frameworks: ['appium'], languages: ['typescript'], domains: ['mobile'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Espresso Android Testing', slug: 'espresso-android', description: 'Android UI testing framework with synchronization, view matchers, and actions', authorName: 'thetestingacademy', qualityScore: 84, installCount: 16, weeklyInstalls: 16, testingTypes: ['mobile', 'e2e'], frameworks: ['appium'], languages: ['java'], domains: ['mobile'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Maestro Mobile Testing', slug: 'maestro-mobile', description: 'Simple mobile UI testing with YAML flows for iOS and Android without complex setup', authorName: 'thetestingacademy', qualityScore: 88, installCount: 22, weeklyInstalls: 22, testingTypes: ['mobile', 'e2e'], frameworks: ['appium'], languages: ['typescript'], domains: ['mobile'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Snapshot Testing', slug: 'snapshot-testing', description: 'Component and API snapshot testing to detect unexpected changes across releases', authorName: 'thetestingacademy', qualityScore: 82, installCount: 20, weeklyInstalls: 20, testingTypes: ['unit', 'visual'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Mutation Testing', slug: 'mutation-testing', description: 'Test quality verification with Stryker mutation testing for JavaScript and TypeScript', authorName: 'thetestingacademy', qualityScore: 86, installCount: 17, weeklyInstalls: 17, testingTypes: ['unit', 'code-quality'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Property-Based Testing', slug: 'property-based-testing', description: 'Generative testing with fast-check to discover edge cases automatically', authorName: 'thetestingacademy', qualityScore: 84, installCount: 13, weeklyInstalls: 13, testingTypes: ['unit', 'tdd'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'ESLint Testing Rules', slug: 'eslint-testing', description: 'Enforce testing best practices with ESLint rules for Jest, Testing Library, and Cypress', authorName: 'thetestingacademy', qualityScore: 81, installCount: 25, weeklyInstalls: 25, testingTypes: ['code-quality'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Lighthouse Performance', slug: 'lighthouse-performance', description: 'Automated performance, accessibility, and SEO auditing with Google Lighthouse', authorName: 'thetestingacademy', qualityScore: 89, installCount: 36, weeklyInstalls: 36, testingTypes: ['performance', 'accessibility'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true },
    { name: 'Docker Test Containers', slug: 'docker-testcontainers', description: 'Integration testing with throwaway Docker containers for databases and external services', authorName: 'thetestingacademy', qualityScore: 87, installCount: 23, weeklyInstalls: 23, testingTypes: ['integration'], frameworks: ['jest', 'pytest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'MSW API Mocking', slug: 'msw-mocking', description: 'Mock Service Worker for seamless API mocking in browser and Node.js environments', authorName: 'thetestingacademy', qualityScore: 88, installCount: 33, weeklyInstalls: 33, testingTypes: ['unit', 'integration'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Code Coverage Analysis', slug: 'code-coverage', description: 'Track test coverage with Istanbul/nyc, generate reports, and enforce thresholds', authorName: 'thetestingacademy', qualityScore: 85, installCount: 30, weeklyInstalls: 30, testingTypes: ['unit', 'code-quality'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'TDD Red-Green-Refactor', slug: 'tdd-patterns', description: 'Test-driven development workflow patterns with red-green-refactor cycle and refactoring techniques', authorName: 'thetestingacademy', qualityScore: 83, installCount: 19, weeklyInstalls: 19, testingTypes: ['tdd', 'unit'], frameworks: ['jest'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: false, verified: true },
    { name: 'Selenium Advanced POM Framework', slug: 'selenium-advance-pom', description: 'Advanced Selenium WebDriver framework with three Page Object Model patterns (Basic POM, Improved POM, Page Factory), retry mechanisms, Allure reporting, Excel data-driven testing, and Selenoid grid support.', authorName: 'thetestingacademy', qualityScore: 90, installCount: 34, weeklyInstalls: 34, testingTypes: ['e2e'], frameworks: ['selenium'], languages: ['java'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true, githubUrl: 'https://github.com/PramodDutta/ATB11xSeleniumAdvanceFramework' },
    { name: 'REST Assured API Automation Framework', slug: 'restassured-api-framework', description: 'Production-grade REST API automation framework with REST Assured, POJO serialization using GSON, PayloadManager pattern, E2E integration workflows with TestNG ITestContext, and Allure reporting.', authorName: 'thetestingacademy', qualityScore: 89, installCount: 28, weeklyInstalls: 28, testingTypes: ['api', 'integration'], frameworks: ['rest-assured'], languages: ['java'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt'], featured: true, verified: true, githubUrl: 'https://github.com/PramodDutta/APIAutomationFramworkATB11x' },
    // --- 50 New QA Skills by Pramod ---
    // Bug Hunting Skills (1-11)
    { name: 'Dead Link Detector', slug: 'dead-link-detector', description: 'Automated detection and reporting of broken links, missing resources, and orphaned pages across web applications using crawl-based and DOM-based strategies', authorName: 'Pramod', qualityScore: 87, installCount: 12, weeklyInstalls: 12, testingTypes: ['e2e', 'code-quality'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Console Error Hunter', slug: 'console-error-hunter', description: 'Systematically detect, capture, and categorize browser console errors, warnings, and unhandled exceptions during automated test execution', authorName: 'Pramod', qualityScore: 86, installCount: 10, weeklyInstalls: 10, testingTypes: ['e2e', 'code-quality'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Form Validation Breaker', slug: 'form-validation-breaker', description: 'Exhaustive testing of form validation logic including boundary values, injection payloads, encoding edge cases, and client-server validation bypass techniques', authorName: 'Pramod', qualityScore: 89, installCount: 15, weeklyInstalls: 15, testingTypes: ['security', 'e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: true, verified: true },
    { name: 'Race Condition Finder', slug: 'race-condition-finder', description: 'Detect and reproduce race conditions in web applications including double submissions, concurrent state mutations, and timing-dependent UI bugs', authorName: 'Pramod', qualityScore: 88, installCount: 11, weeklyInstalls: 11, testingTypes: ['e2e', 'integration'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Memory Leak Detector', slug: 'memory-leak-detector', description: 'Identify and diagnose memory leaks in web applications through heap analysis, DOM node counting, detached element detection, and performance profiling', authorName: 'Pramod', qualityScore: 87, installCount: 9, weeklyInstalls: 9, testingTypes: ['performance', 'e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Auth Bypass Tester', slug: 'auth-bypass-tester', description: 'Comprehensive authentication and authorization bypass testing including session hijacking, privilege escalation, JWT manipulation, and access control verification', authorName: 'Pramod', qualityScore: 91, installCount: 18, weeklyInstalls: 18, testingTypes: ['security'], frameworks: ['playwright'], languages: ['typescript', 'javascript', 'python'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: true, verified: true },
    { name: 'API Contract Validator', slug: 'api-contract-validator', description: 'Validate API responses against OpenAPI/Swagger specifications, JSON Schema definitions, and consumer-driven contracts to prevent breaking changes', authorName: 'Pramod', qualityScore: 88, installCount: 14, weeklyInstalls: 14, testingTypes: ['contract', 'api'], frameworks: ['postman', 'rest-assured'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Responsive Layout Breaker', slug: 'responsive-layout-breaker', description: 'Systematically test responsive web layouts across viewports, detecting overflow, text truncation, overlapping elements, and broken grid layouts', authorName: 'Pramod', qualityScore: 86, installCount: 8, weeklyInstalls: 8, testingTypes: ['visual', 'e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Dark Mode Bug Finder', slug: 'dark-mode-bug-finder', description: 'Detect visual defects in dark mode implementations including contrast issues, hardcoded colors, missing theme tokens, and inconsistent component theming', authorName: 'Pramod', qualityScore: 85, installCount: 7, weeklyInstalls: 7, testingTypes: ['visual', 'e2e', 'accessibility'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Timezone Bug Hunter', slug: 'timezone-bug-hunter', description: 'Detect timezone-related bugs including incorrect date conversions, DST edge cases, locale formatting issues, and UTC offset miscalculations across application layers', authorName: 'Pramod', qualityScore: 87, installCount: 10, weeklyInstalls: 10, testingTypes: ['e2e', 'integration'], frameworks: ['playwright'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Localization Bug Finder', slug: 'localization-bug-finder', description: 'Detect localization and internationalization defects including untranslated strings, text expansion overflow, RTL layout issues, and locale-specific formatting errors', authorName: 'Pramod', qualityScore: 86, installCount: 8, weeklyInstalls: 8, testingTypes: ['e2e', 'accessibility'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    // Infrastructure & Resilience Skills (12-17)
    { name: 'N+1 Query Detector', slug: 'n-plus-one-query-detector', description: 'Detect and eliminate N+1 query problems in database-backed applications through query counting, execution plan analysis, and ORM configuration auditing', authorName: 'Pramod', qualityScore: 89, installCount: 13, weeklyInstalls: 13, testingTypes: ['performance', 'database'], frameworks: [], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: true, verified: true },
    { name: 'Stale Cache Finder', slug: 'stale-cache-finder', description: 'Identify stale cache issues across browser cache, CDN layers, API response caching, and application-level caches that cause users to see outdated content', authorName: 'Pramod', qualityScore: 85, installCount: 7, weeklyInstalls: 7, testingTypes: ['integration', 'e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Error Boundary Tester', slug: 'error-boundary-tester', description: 'Validate error boundary implementations in React and other frameworks ensuring graceful degradation, proper fallback UI rendering, and error recovery flows', authorName: 'Pramod', qualityScore: 86, installCount: 9, weeklyInstalls: 9, testingTypes: ['e2e', 'unit'], frameworks: ['playwright', 'jest', 'vitest'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'WebSocket Bug Finder', slug: 'websocket-bug-finder', description: 'Test WebSocket connections for reliability including reconnection logic, message ordering, heartbeat mechanisms, and connection state management under adverse conditions', authorName: 'Pramod', qualityScore: 87, installCount: 8, weeklyInstalls: 8, testingTypes: ['integration', 'e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Notification Spam Detector', slug: 'notification-spam-detector', description: 'Test notification systems for spam behavior including duplicate alerts, missing throttling, incorrect delivery channels, and notification preference violations', authorName: 'Pramod', qualityScore: 84, installCount: 6, weeklyInstalls: 6, testingTypes: ['integration', 'e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Offline Mode Tester', slug: 'offline-mode-tester', description: 'Validate progressive web app offline functionality including service worker caching, offline data persistence, sync-on-reconnect behavior, and graceful degradation', authorName: 'Pramod', qualityScore: 85, installCount: 7, weeklyInstalls: 7, testingTypes: ['e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    // UX & Usability Skills (18-28)
    { name: 'Angry User Simulator', slug: 'angry-user-simulator', description: 'Simulate aggressive user behavior patterns including rapid clicking, random navigation, form abuse, tab spamming, and unexpected interaction sequences to find UI resilience issues', authorName: 'Pramod', qualityScore: 88, installCount: 14, weeklyInstalls: 14, testingTypes: ['e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: true, verified: true },
    { name: 'First-Time User Tester', slug: 'first-time-user-tester', description: 'Validate the first-time user experience including onboarding flows, empty states, tutorial completion, progressive disclosure, and initial setup wizards', authorName: 'Pramod', qualityScore: 84, installCount: 7, weeklyInstalls: 7, testingTypes: ['e2e', 'accessibility'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Accessibility Auditor', slug: 'accessibility-auditor', description: 'Comprehensive WCAG 2.1 AA compliance testing combining automated axe-core scans with manual keyboard navigation, screen reader compatibility, and focus management verification', authorName: 'Pramod', qualityScore: 90, installCount: 16, weeklyInstalls: 16, testingTypes: ['accessibility', 'e2e'], frameworks: ['playwright', 'axe-core'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: true, verified: true },
    { name: 'UX Friction Logger', slug: 'ux-friction-logger', description: 'Identify and log user experience friction points including excessive clicks, confusing navigation, slow interactions, and workflow bottlenecks through automated heuristic analysis', authorName: 'Pramod', qualityScore: 85, installCount: 8, weeklyInstalls: 8, testingTypes: ['e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Error Message Reviewer', slug: 'error-message-reviewer', description: 'Audit error messages across web applications for clarity, helpfulness, consistency, localization readiness, and security information leakage', authorName: 'Pramod', qualityScore: 83, installCount: 6, weeklyInstalls: 6, testingTypes: ['e2e', 'code-quality'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Loading State Tester', slug: 'loading-state-tester', description: 'Verify loading states, skeleton screens, spinners, and progress indicators across all data-fetching scenarios including slow networks, errors, and partial loads', authorName: 'Pramod', qualityScore: 86, installCount: 9, weeklyInstalls: 9, testingTypes: ['e2e', 'performance'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Mobile Gesture Tester', slug: 'mobile-gesture-tester', description: 'Test touch interactions and mobile gestures including swipe, pinch-zoom, long-press, drag-and-drop, pull-to-refresh, and multi-touch behaviors across mobile viewports', authorName: 'Pramod', qualityScore: 85, installCount: 8, weeklyInstalls: 8, testingTypes: ['mobile', 'e2e'], frameworks: ['playwright', 'appium'], languages: ['typescript', 'javascript'], domains: ['mobile', 'web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Page Speed Critic', slug: 'page-speed-critic', description: 'Automated page performance auditing covering Core Web Vitals, resource loading analysis, render-blocking detection, and performance budget enforcement', authorName: 'Pramod', qualityScore: 88, installCount: 13, weeklyInstalls: 13, testingTypes: ['performance'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Search Quality Tester', slug: 'search-quality-tester', description: 'Evaluate search functionality quality including relevance ranking, typo tolerance, faceted filtering, autocomplete accuracy, and zero-results handling', authorName: 'Pramod', qualityScore: 86, installCount: 9, weeklyInstalls: 9, testingTypes: ['e2e', 'integration'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Empty State Reviewer', slug: 'empty-state-reviewer', description: 'Audit empty states across web applications ensuring proper messaging, helpful CTAs, illustration rendering, and graceful handling when data is unavailable', authorName: 'Pramod', qualityScore: 83, installCount: 6, weeklyInstalls: 6, testingTypes: ['e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Cognitive Load Analyzer', slug: 'cognitive-load-analyzer', description: 'Analyze web application interfaces for cognitive overload using automated heuristics covering information density, choice complexity, visual hierarchy, and interaction patterns', authorName: 'Pramod', qualityScore: 84, installCount: 7, weeklyInstalls: 7, testingTypes: ['e2e', 'accessibility'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    // Test Generation Skills (29-42)
    { name: 'Test Case Generator from User Stories', slug: 'test-case-generator-user-stories', description: 'Automatically generate comprehensive test cases from user stories and acceptance criteria using BDD patterns, equivalence partitioning, and risk-based prioritization', authorName: 'Pramod', qualityScore: 87, installCount: 11, weeklyInstalls: 11, testingTypes: ['bdd', 'tdd'], frameworks: ['cucumber'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Boundary Value Generator', slug: 'boundary-value-generator', description: 'Generate boundary value test cases for numeric ranges, string lengths, date ranges, collection sizes, and domain-specific constraints using systematic analysis techniques', authorName: 'Pramod', qualityScore: 86, installCount: 10, weeklyInstalls: 10, testingTypes: ['unit', 'integration'], frameworks: ['jest', 'vitest', 'pytest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'API Test Suite Generator', slug: 'api-test-suite-generator', description: 'Automatically generate comprehensive API test suites from OpenAPI specifications covering CRUD operations, error handling, authentication, pagination, and edge cases', authorName: 'Pramod', qualityScore: 89, installCount: 15, weeklyInstalls: 15, testingTypes: ['api', 'contract'], frameworks: ['playwright', 'postman', 'rest-assured'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: true, verified: true },
    { name: 'Pairwise Test Generator', slug: 'pairwise-test-generator', description: 'Generate optimized test combinations using pairwise (all-pairs) testing algorithms to achieve maximum coverage with minimum test cases across multiple input parameters', authorName: 'Pramod', qualityScore: 85, installCount: 8, weeklyInstalls: 8, testingTypes: ['unit', 'integration'], frameworks: ['jest', 'vitest', 'pytest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Mutation Test Generator', slug: 'mutation-test-generator', description: 'Generate and evaluate mutation tests to assess test suite effectiveness by introducing controlled code mutations and verifying test detection rates', authorName: 'Pramod', qualityScore: 86, installCount: 9, weeklyInstalls: 9, testingTypes: ['unit', 'code-quality'], frameworks: ['jest', 'vitest'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Test Data Factory', slug: 'test-data-factory', description: 'Build reusable test data factories with builder patterns, realistic fake data generation, relationship handling, and database seeding for consistent test environments', authorName: 'Pramod', qualityScore: 87, installCount: 11, weeklyInstalls: 11, testingTypes: ['unit', 'integration', 'e2e'], frameworks: ['jest', 'vitest', 'playwright', 'pytest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Regression Suite from Bug Reports', slug: 'regression-suite-bug-reports', description: 'Automatically generate regression test cases from bug reports and incident post-mortems to prevent previously fixed defects from recurring', authorName: 'Pramod', qualityScore: 85, installCount: 8, weeklyInstalls: 8, testingTypes: ['e2e', 'integration'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Exploratory Test Charter Generator', slug: 'exploratory-test-charter-generator', description: 'Generate structured exploratory testing charters with focused missions, time-boxed sessions, risk-based areas, and standardized note-taking templates for systematic exploration', authorName: 'Pramod', qualityScore: 84, installCount: 7, weeklyInstalls: 7, testingTypes: ['e2e'], frameworks: [], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Database Migration Test Generator', slug: 'database-migration-test-generator', description: 'Generate tests for database migration safety covering schema changes, data integrity preservation, rollback verification, and zero-downtime migration validation', authorName: 'Pramod', qualityScore: 87, installCount: 10, weeklyInstalls: 10, testingTypes: ['database', 'integration'], frameworks: ['jest', 'vitest', 'pytest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'State Machine Test Generator', slug: 'state-machine-test-generator', description: 'Generate comprehensive test cases from state machine models covering all states, transitions, guard conditions, and invalid transition attempts for workflow-heavy features', authorName: 'Pramod', qualityScore: 86, installCount: 9, weeklyInstalls: 9, testingTypes: ['unit', 'integration'], frameworks: ['jest', 'vitest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Negative Test Generator', slug: 'negative-test-generator', description: 'Systematically generate negative test cases covering invalid inputs, unauthorized actions, missing required fields, exceeded limits, and malformed request payloads', authorName: 'Pramod', qualityScore: 87, installCount: 11, weeklyInstalls: 11, testingTypes: ['unit', 'integration', 'security'], frameworks: ['jest', 'vitest', 'pytest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Screenshot Baseline Generator', slug: 'screenshot-baseline-generator', description: 'Generate and maintain visual regression screenshot baselines with intelligent diffing, responsive breakpoint coverage, and dynamic content masking strategies', authorName: 'Pramod', qualityScore: 86, installCount: 9, weeklyInstalls: 9, testingTypes: ['visual', 'e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Contract Test Generator', slug: 'contract-test-generator', description: 'Generate consumer-driven contract tests using Pact framework to verify API provider-consumer compatibility and prevent integration breaking changes', authorName: 'Pramod', qualityScore: 88, installCount: 12, weeklyInstalls: 12, testingTypes: ['contract', 'api'], frameworks: ['pact'], languages: ['typescript', 'javascript', 'java'], domains: ['api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Performance Test Scenario Generator', slug: 'performance-test-scenario-generator', description: 'Generate realistic performance test scenarios with load profiles, ramp-up patterns, think times, and acceptance criteria derived from production traffic analysis', authorName: 'Pramod', qualityScore: 87, installCount: 10, weeklyInstalls: 10, testingTypes: ['performance', 'load'], frameworks: ['k6', 'jmeter'], languages: ['typescript', 'javascript'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    // CI/CD & Test Management Skills (43-50)
    { name: 'Flaky Test Quarantine', slug: 'flaky-test-quarantine', description: 'Detect, quarantine, and systematically fix flaky tests with automated retry analysis, root cause categorization, and CI pipeline integration for test reliability', authorName: 'Pramod', qualityScore: 88, installCount: 14, weeklyInstalls: 14, testingTypes: ['code-quality', 'e2e'], frameworks: ['playwright', 'jest', 'vitest'], languages: ['typescript', 'javascript'], domains: ['devops'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: true, verified: true },
    { name: 'Test Coverage Gap Finder', slug: 'test-coverage-gap-finder', description: 'Identify untested code paths, uncovered branches, and missing test scenarios using coverage analysis, risk mapping, and change-based coverage tracking', authorName: 'Pramod', qualityScore: 87, installCount: 12, weeklyInstalls: 12, testingTypes: ['code-quality', 'unit'], frameworks: ['jest', 'vitest', 'pytest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['web', 'api'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Allure Report Generator', slug: 'allure-report-generator', description: 'Configure and generate rich Allure test reports with test categorization, historical trends, environment details, and CI/CD integration for comprehensive test visibility', authorName: 'Pramod', qualityScore: 86, installCount: 10, weeklyInstalls: 10, testingTypes: ['e2e', 'integration'], frameworks: ['playwright', 'jest', 'pytest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['devops'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'PR Test Impact Analyzer', slug: 'pr-test-impact-analyzer', description: 'Analyze pull request code changes to determine which tests are affected, recommend test execution order, and identify missing test coverage for modified code paths', authorName: 'Pramod', qualityScore: 87, installCount: 11, weeklyInstalls: 11, testingTypes: ['code-quality', 'tdd'], frameworks: ['jest', 'vitest'], languages: ['typescript', 'javascript'], domains: ['devops'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Production Smoke Suite', slug: 'production-smoke-suite', description: 'Design and maintain lightweight production smoke test suites that verify critical user journeys, API health, and infrastructure availability after deployments', authorName: 'Pramod', qualityScore: 89, installCount: 15, weeklyInstalls: 15, testingTypes: ['e2e'], frameworks: ['playwright'], languages: ['typescript', 'javascript'], domains: ['web', 'api', 'devops'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: true, verified: true },
    { name: 'Test Debt Calculator', slug: 'test-debt-calculator', description: 'Quantify and track test technical debt including missing tests, outdated assertions, disabled tests, inadequate coverage, and maintenance burden across the test suite', authorName: 'Pramod', qualityScore: 84, installCount: 7, weeklyInstalls: 7, testingTypes: ['code-quality'], frameworks: ['jest', 'vitest', 'pytest'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['devops'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'Changelog Test Mapper', slug: 'changelog-test-mapper', description: 'Map changelog entries and release notes to corresponding test cases ensuring every shipped feature and bugfix has associated test verification', authorName: 'Pramod', qualityScore: 83, installCount: 6, weeklyInstalls: 6, testingTypes: ['code-quality'], frameworks: [], languages: ['typescript', 'javascript'], domains: ['devops'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
    { name: 'CI Pipeline Optimizer', slug: 'ci-pipeline-optimizer', description: 'Optimize CI/CD test pipeline execution through intelligent test splitting, parallelization, caching strategies, and selective test execution to reduce pipeline duration', authorName: 'Pramod', qualityScore: 88, installCount: 13, weeklyInstalls: 13, testingTypes: ['code-quality'], frameworks: ['jest', 'vitest', 'playwright'], languages: ['typescript', 'javascript', 'python', 'java'], domains: ['devops'], agents: ['claude-code', 'cursor', 'github-copilot', 'windsurf', 'codex', 'aider', 'continue', 'cline', 'zed', 'bolt', 'gemini-cli', 'amp'], featured: false, verified: true },
  ];

  for (const skill of seedSkills) {
    const fullDescription = readSkillBody(skill.slug);
    await db.insert(skills).values({ ...skill, fullDescription }).onConflictDoUpdate({
      target: skills.slug,
      set: {
        installCount: skill.installCount,
        weeklyInstalls: skill.weeklyInstalls,
        qualityScore: skill.qualityScore,
        fullDescription,
      },
    });
  }

  console.log(`Seeded ${seedSkills.length} skills`);

  // Seed skill packs
  console.log('Seeding skill packs...');

  const seedPacks = [
    {
      name: 'Complete Playwright Suite',
      slug: 'playwright-suite',
      description: 'Everything you need for Playwright testing — E2E, API, visual regression, and accessibility.',
      featured: true,
      installCount: 38,
      skillSlugs: ['playwright-e2e', 'playwright-api', 'visual-regression', 'axe-accessibility'],
    },
    {
      name: 'API Testing Toolkit',
      slug: 'api-testing-toolkit',
      description: 'Comprehensive API testing with REST, GraphQL, contract testing, and performance.',
      featured: true,
      installCount: 21,
      skillSlugs: ['playwright-api', 'rest-assured-api', 'postman-api', 'contract-testing-pact', 'k6-performance'],
    },
    {
      name: 'Performance & Load Testing',
      slug: 'performance-suite',
      description: 'Load test your applications with k6 and JMeter, plus CI/CD integration.',
      featured: false,
      installCount: 12,
      skillSlugs: ['k6-performance', 'jmeter-load', 'cicd-pipeline'],
    },
    {
      name: 'Security & Compliance',
      slug: 'security-compliance',
      description: 'OWASP security testing and accessibility compliance in one pack.',
      featured: false,
      installCount: 9,
      skillSlugs: ['owasp-security', 'axe-accessibility'],
    },
    {
      name: 'Mobile Testing Kit',
      slug: 'mobile-testing-kit',
      description: 'Mobile app testing automation for iOS and Android with Appium and cross-platform tools.',
      featured: false,
      installCount: 5,
      skillSlugs: ['appium-mobile', 'bug-report-writing'],
    },
    {
      name: 'Full Stack QA',
      slug: 'full-stack-qa',
      description: 'A curated mix of the best featured QA skills across all testing types.',
      featured: true,
      installCount: 31,
      skillSlugs: ['playwright-e2e', 'cypress-e2e', 'k6-performance', 'owasp-security', 'jest-unit', 'pytest-patterns', 'cicd-pipeline', 'test-data-generation'],
    },
  ];

  for (const pack of seedPacks) {
    const { skillSlugs, ...packData } = pack;

    // Insert the pack
    await db.insert(skillPacks).values(packData).onConflictDoNothing();

    // Look up the pack ID by slug
    const [insertedPack] = await db
      .select({ id: skillPacks.id })
      .from(skillPacks)
      .where(eq(skillPacks.slug, pack.slug))
      .limit(1);

    if (!insertedPack) continue;

    // Link skills to pack
    for (let i = 0; i < skillSlugs.length; i++) {
      const [skill] = await db
        .select({ id: skills.id })
        .from(skills)
        .where(eq(skills.slug, skillSlugs[i]))
        .limit(1);

      if (skill) {
        await db
          .insert(skillPackItems)
          .values({
            packId: insertedPack.id,
            skillId: skill.id,
            order: i,
          })
          .onConflictDoNothing();
      }
    }
  }

  console.log(`Seeded ${seedPacks.length} skill packs with items`);
  console.log('Seed complete!');
}

seed().catch(console.error);
