import type { AgentDefinition } from '../types/agent';

export const AGENTS: AgentDefinition[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    slug: 'claude-code',
    description: 'Anthropic CLI coding agent',
    configDir: '~/.claude',
    skillsDir: '~/.claude/commands',
    configFile: 'CLAUDE.md',
    installMethod: 'symlink',
    website: 'https://claude.ai/code',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    slug: 'cursor',
    description: 'AI-first code editor',
    configDir: '.cursor',
    skillsDir: '.cursor/rules',
    configFile: '.cursorrules',
    installMethod: 'copy',
    website: 'https://cursor.com',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    description: 'GitHub AI coding assistant',
    configDir: '.github',
    skillsDir: '.github/copilot-instructions',
    configFile: '.github/copilot-instructions.md',
    installMethod: 'copy',
    website: 'https://github.com/features/copilot',
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    slug: 'windsurf',
    description: 'Codeium AI-powered IDE',
    configDir: '.windsurf',
    skillsDir: '.windsurf/rules',
    configFile: '.windsurfrules',
    installMethod: 'copy',
    website: 'https://windsurf.com',
  },
  {
    id: 'codex',
    name: 'Codex CLI',
    slug: 'codex',
    description: 'OpenAI terminal coding agent',
    configDir: '~/.codex',
    skillsDir: '~/.codex/instructions',
    configFile: 'AGENTS.md',
    installMethod: 'symlink',
    website: 'https://openai.com/codex',
  },
  {
    id: 'aider',
    name: 'Aider',
    slug: 'aider',
    description: 'AI pair programming in terminal',
    configDir: '.aider',
    skillsDir: '.aider/conventions',
    configFile: '.aider.conf.yml',
    installMethod: 'copy',
    website: 'https://aider.chat',
  },
  {
    id: 'continue',
    name: 'Continue',
    slug: 'continue',
    description: 'Open-source AI code assistant',
    configDir: '.continue',
    skillsDir: '.continue/rules',
    configFile: '.continue/config.json',
    installMethod: 'copy',
    website: 'https://continue.dev',
  },
  {
    id: 'cline',
    name: 'Cline',
    slug: 'cline',
    description: 'Autonomous coding agent for VS Code',
    configDir: '.cline',
    skillsDir: '.cline/rules',
    configFile: '.clinerules',
    installMethod: 'copy',
    website: 'https://cline.bot',
  },
  {
    id: 'zed',
    name: 'Zed AI',
    slug: 'zed',
    description: 'High-performance editor with AI',
    configDir: '.zed',
    skillsDir: '.zed/rules',
    configFile: '.zed/settings.json',
    installMethod: 'copy',
    website: 'https://zed.dev',
  },
  {
    id: 'bolt',
    name: 'Bolt.new',
    slug: 'bolt',
    description: 'Full-stack web dev AI agent',
    configDir: '.bolt',
    skillsDir: '.bolt/rules',
    configFile: '.bolt/config.json',
    installMethod: 'copy',
    website: 'https://bolt.new',
  },
  {
    id: 'lovable',
    name: 'Lovable',
    slug: 'lovable',
    description: 'AI web app builder',
    configDir: '.lovable',
    skillsDir: '.lovable/rules',
    configFile: '.lovable/config.json',
    installMethod: 'copy',
    website: 'https://lovable.dev',
  },
  {
    id: 'v0',
    name: 'v0',
    slug: 'v0',
    description: 'Vercel AI UI generator',
    configDir: '.v0',
    skillsDir: '.v0/rules',
    configFile: '.v0/config.json',
    installMethod: 'copy',
    website: 'https://v0.dev',
  },
  {
    id: 'devin',
    name: 'Devin',
    slug: 'devin',
    description: 'Autonomous AI software engineer',
    configDir: '.devin',
    skillsDir: '.devin/rules',
    configFile: '.devin/config.json',
    installMethod: 'copy',
    website: 'https://devin.ai',
  },
  {
    id: 'sourcegraph-cody',
    name: 'Sourcegraph Cody',
    slug: 'cody',
    description: 'AI coding assistant by Sourcegraph',
    configDir: '.cody',
    skillsDir: '.cody/rules',
    configFile: '.cody/config.json',
    installMethod: 'copy',
    website: 'https://sourcegraph.com/cody',
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    slug: 'tabnine',
    description: 'AI code completions',
    configDir: '.tabnine',
    skillsDir: '.tabnine/rules',
    configFile: '.tabnine/config.json',
    installMethod: 'copy',
    website: 'https://tabnine.com',
  },
  {
    id: 'replit-agent',
    name: 'Replit Agent',
    slug: 'replit',
    description: 'AI agent in Replit IDE',
    configDir: '.replit',
    skillsDir: '.replit/rules',
    configFile: '.replit',
    installMethod: 'copy',
    website: 'https://replit.com',
  },
  {
    id: 'amazon-q',
    name: 'Amazon Q Developer',
    slug: 'amazon-q',
    description: 'AWS AI coding assistant',
    configDir: '.amazonq',
    skillsDir: '.amazonq/rules',
    configFile: '.amazonq/config.json',
    installMethod: 'copy',
    website: 'https://aws.amazon.com/q/developer/',
  },
  {
    id: 'jetbrains-ai',
    name: 'JetBrains AI',
    slug: 'jetbrains-ai',
    description: 'AI assistant for JetBrains IDEs',
    configDir: '.idea',
    skillsDir: '.idea/ai-rules',
    configFile: '.idea/ai-rules/config.json',
    installMethod: 'copy',
    website: 'https://jetbrains.com/ai/',
  },
  {
    id: 'gemini-code-assist',
    name: 'Gemini Code Assist',
    slug: 'gemini',
    description: 'Google AI coding assistant',
    configDir: '.gemini',
    skillsDir: '.gemini/rules',
    configFile: '.gemini/config.json',
    installMethod: 'copy',
    website: 'https://cloud.google.com/gemini/docs/codeassist',
  },
  {
    id: 'supermaven',
    name: 'Supermaven',
    slug: 'supermaven',
    description: 'Fast AI code completions',
    configDir: '.supermaven',
    skillsDir: '.supermaven/rules',
    configFile: '.supermaven/config.json',
    installMethod: 'copy',
    website: 'https://supermaven.com',
  },
  {
    id: 'double',
    name: 'Double',
    slug: 'double',
    description: 'AI coding agent',
    configDir: '.double',
    skillsDir: '.double/rules',
    configFile: '.double/config.json',
    installMethod: 'copy',
    website: 'https://double.bot',
  },
  {
    id: 'aide',
    name: 'Aide',
    slug: 'aide',
    description: 'AI-native IDE',
    configDir: '.aide',
    skillsDir: '.aide/rules',
    configFile: '.aide/config.json',
    installMethod: 'copy',
    website: 'https://aide.dev',
  },
  {
    id: 'void',
    name: 'Void',
    slug: 'void',
    description: 'Open-source AI code editor',
    configDir: '.void',
    skillsDir: '.void/rules',
    configFile: '.void/config.json',
    installMethod: 'copy',
    website: 'https://voideditor.com',
  },
  {
    id: 'trae',
    name: 'Trae',
    slug: 'trae',
    description: 'AI IDE by ByteDance',
    configDir: '.trae',
    skillsDir: '.trae/rules',
    configFile: '.trae/config.json',
    installMethod: 'copy',
    website: 'https://trae.ai',
  },
  {
    id: 'roo-code',
    name: 'Roo Code',
    slug: 'roo-code',
    description: 'AI coding assistant',
    configDir: '.roo',
    skillsDir: '.roo/rules',
    configFile: '.roo/config.json',
    installMethod: 'copy',
    website: 'https://roocode.com',
  },
  {
    id: 'augment',
    name: 'Augment Code',
    slug: 'augment',
    description: 'AI software development platform',
    configDir: '.augment',
    skillsDir: '.augment/rules',
    configFile: '.augment/config.json',
    installMethod: 'copy',
    website: 'https://augmentcode.com',
  },
  {
    id: 'privy',
    name: 'Privy',
    slug: 'privy',
    description: 'Local AI coding assistant',
    configDir: '.privy',
    skillsDir: '.privy/rules',
    configFile: '.privy/config.json',
    installMethod: 'copy',
    website: 'https://privy.dev',
  },
];

export const AGENT_IDS = AGENTS.map((a) => a.id);
export type AgentId = (typeof AGENTS)[number]['id'];
