export type SearchIntent =
  | 'informational'
  | 'tutorial'
  | 'implementation'
  | 'troubleshooting'
  | 'comparison'
  | 'security';

export interface SeoTopicPlanItem {
  slug: string;
  title: string;
  primaryKeyword: string;
  intent: SearchIntent;
  role: 'pillar' | 'child';
  publicationWave: 1 | 2;
  canonicalStrategy: 'upgrade' | 'new';
}

export interface SeoTopicClusterPlan {
  id: string;
  name: string;
  audience: string;
  rationale: string;
  evidenceSources: string[];
  topics: SeoTopicPlanItem[];
}

export const seoTopicClusters2026: SeoTopicClusterPlan[] = [
  {
    id: 'playwright-core',
    name: 'Playwright Testing in 2026',
    audience: 'QA engineers and developers building browser automation suites',
    rationale:
      'Protect the established Playwright authority while covering version 1.60 and 1.61 features with distinct task-level intent.',
    evidenceSources: [
      'https://playwright.dev/docs/release-notes',
      'https://playwright.dev/docs/best-practices',
      'https://playwright.dev/docs/locators',
    ],
    topics: [
      {
        slug: 'playwright-e2e-complete-guide',
        title: 'Playwright Testing Complete Guide for Reliable E2E Automation in 2026',
        primaryKeyword: 'playwright testing guide',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-1-61-webauthn-passkeys-guide-2026',
        title: 'Playwright 1.61 WebAuthn Passkey Testing with Virtual Authenticators',
        primaryKeyword: 'playwright webauthn passkey testing',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-1-61-web-storage-api-guide-2026',
        title: 'Playwright localStorage and sessionStorage API Guide for Version 1.61',
        primaryKeyword: 'playwright localstorage sessionstorage api',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-locators-best-practices-2026',
        title: 'Playwright Locators Best Practices: Roles, Strictness, and Stability',
        primaryKeyword: 'playwright locators best practices',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-browser-context-guide-2026',
        title: 'Playwright BrowserContext Guide for Isolation and Parallel Sessions',
        primaryKeyword: 'playwright browser context',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-starthar-tracing-guide',
        title: 'Playwright tracing.startHar Guide for Network Evidence and Debugging',
        primaryKeyword: 'playwright tracing starthar',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-drop-api-drag-and-drop',
        title: 'Playwright locator.drop Tutorial for File and DataTransfer Testing',
        primaryKeyword: 'playwright locator drop',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-aria-snapshot-boxes-ai-guide-2026',
        title: 'Playwright ARIA Snapshot Boxes for AI-Assisted Browser Testing',
        primaryKeyword: 'playwright aria snapshot boxes',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-video-retention-modes-guide-2026',
        title: 'Playwright Video Retention Modes Explained for CI Failures and Retries',
        primaryKeyword: 'playwright video retention modes',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-test-abort-guardrail-guide-2026',
        title: 'Playwright test.abort Guide for Safety Guardrails in Test Fixtures',
        primaryKeyword: 'playwright test abort',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
  {
    id: 'playwright-cli',
    name: 'Playwright CLI for Coding Agents',
    audience: 'QA engineers and coding-agent users who automate browsers from a terminal',
    rationale:
      'The official agent CLI now has dedicated capabilities, sessions, dashboard, test debugging, tracing, and video workflows that older CLI articles do not cover.',
    evidenceSources: [
      'https://playwright.dev/agent-cli/capabilities',
      'https://playwright.dev/docs/release-notes',
      'https://playwright.dev/docs/test-cli',
    ],
    topics: [
      {
        slug: 'playwright-cli-complete-guide-2026',
        title: 'Playwright CLI Complete Guide for Browser Automation and AI Agents',
        primaryKeyword: 'playwright cli',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-cli-install-quickstart-2026',
        title: 'How to Install Playwright CLI Skills in Codex and Claude Code',
        primaryKeyword: 'playwright cli install skills',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-cli-accessibility-snapshots-guide-2026',
        title: 'Playwright CLI Accessibility Snapshots and Element References Explained',
        primaryKeyword: 'playwright cli snapshot',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-cli-sessions-dashboard-attach-guide-2026',
        title: 'Run Parallel Playwright CLI Sessions with PLAYWRIGHT_CLI_SESSION',
        primaryKeyword: 'playwright cli parallel sessions',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-cli-debug-tests-traces-agents-guide-2026',
        title: 'Debug Playwright Tests with --debug=cli and Agent Trace Commands',
        primaryKeyword: 'playwright debug cli',
        intent: 'troubleshooting',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-cli-network-mocking-guide-2026',
        title: 'Playwright CLI Network Inspection and Route Mocking Tutorial',
        primaryKeyword: 'playwright cli network mocking',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-cli-storage-state-auth-guide-2026',
        title: 'Playwright CLI Storage State, Cookies, and Authentication Sessions',
        primaryKeyword: 'playwright cli storage state',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-cli-attach-existing-chrome-guide-2026',
        title: 'Attach Playwright CLI to Existing Chrome with CDP or the Extension',
        primaryKeyword: 'playwright cli attach chrome',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-cli-video-chapters-guide-2026',
        title: 'Record Agent Video Receipts with Playwright CLI Chapters and Actions',
        primaryKeyword: 'playwright cli video recording',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-cli-vs-playwright-mcp-2026',
        title: 'Playwright CLI vs Playwright MCP: Which Interface Should Agents Use?',
        primaryKeyword: 'playwright cli vs playwright mcp',
        intent: 'comparison',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
  {
    id: 'playwright-mcp',
    name: 'Playwright MCP Browser Automation',
    audience: 'QA teams connecting AI clients to real browser workflows through MCP',
    rationale:
      'Playwright MCP has expanded configuration, capability, profile, endpoint, and security surfaces that support distinct setup and risk-oriented searches.',
    evidenceSources: [
      'https://github.com/microsoft/playwright-mcp',
      'https://playwright.dev/mcp/tools/assertions',
      'https://modelcontextprotocol.io/docs/tutorials/security/security_best_practices',
    ],
    topics: [
      {
        slug: 'playwright-mcp-browser-automation-guide',
        title: 'Playwright MCP Complete Guide for Browser Automation with AI Agents',
        primaryKeyword: 'playwright mcp',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-mcp-json-configuration-reference',
        title: 'Playwright MCP Server Configuration Reference for QA Teams',
        primaryKeyword: 'playwright mcp configuration',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-mcp-testing-capability-guide-2026',
        title: 'Playwright MCP Testing Capability: Assertions and Test Generation',
        primaryKeyword: 'playwright mcp testing capability',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-mcp-profile-modes-guide-2026',
        title: 'Playwright MCP Persistent, Isolated, and Browser Extension Profiles',
        primaryKeyword: 'playwright mcp isolated profile',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-mcp-security-best-practices-2026',
        title: 'Playwright MCP Security Best Practices for Files, Origins, and Secrets',
        primaryKeyword: 'playwright mcp security',
        intent: 'security',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-mcp-docker-guide-2026',
        title: 'Run Playwright MCP in Docker with Headless Chromium and HTTP',
        primaryKeyword: 'playwright mcp docker',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-mcp-remote-http-endpoint-guide-2026',
        title: 'Playwright MCP Remote HTTP Endpoint Setup for CI and Containers',
        primaryKeyword: 'playwright mcp remote server',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-mcp-codex-cursor-claude-setup-2026',
        title: 'Set Up Playwright MCP in Codex, Cursor, Claude Code, and Copilot',
        primaryKeyword: 'playwright mcp setup coding agents',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-mcp-snapshot-token-optimization-guide-2026',
        title: 'Reduce Playwright MCP Token Use with Snapshots and Image Controls',
        primaryKeyword: 'playwright mcp token usage',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-mcp-workspace-file-access-guide-2026',
        title: 'Test Playwright MCP Workspace Roots and File Access Boundaries',
        primaryKeyword: 'playwright mcp file access',
        intent: 'security',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
  {
    id: 'playwright-agents',
    name: 'Playwright Test Agents',
    audience: 'Teams using Planner, Generator, and Healer loops to create browser tests',
    rationale:
      'The official three-agent workflow creates separate planning, generation, healing, client-loop, and governance intents that should converge on one canonical pillar.',
    evidenceSources: [
      'https://playwright.dev/docs/test-agents',
      'https://playwright.dev/docs/release-notes',
    ],
    topics: [
      {
        slug: 'playwright-test-agents-planner-generator-healer',
        title: 'Playwright Test Agents Complete Guide: Planner, Generator, and Healer',
        primaryKeyword: 'playwright test agents',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-init-agents-guide',
        title: 'npx playwright init-agents Setup Guide for Agentic Test Loops',
        primaryKeyword: 'playwright init agents',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-planner-agent-test-plan-guide-2026',
        title: 'Playwright Planner Agent Guide for High-Coverage Markdown Test Plans',
        primaryKeyword: 'playwright planner agent',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-generator-agent-test-code-guide-2026',
        title: 'Playwright Generator Agent Guide for Maintainable Test Code',
        primaryKeyword: 'playwright generator agent',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-healer-agent-self-healing-tests',
        title: 'Playwright Healer Agent Guide for Repairing Failed Browser Tests',
        primaryKeyword: 'playwright healer agent',
        intent: 'troubleshooting',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'playwright-agents-vscode-loop-guide-2026',
        title: 'Playwright Test Agents with VS Code Agent Loops: Setup and Workflow',
        primaryKeyword: 'playwright agents vscode',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-agents-claude-code-loop-guide-2026',
        title: 'Playwright Test Agents with Claude Code: Planner to Healer Workflow',
        primaryKeyword: 'playwright agents claude code',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-agents-opencode-loop-guide-2026',
        title: 'Playwright Test Agents with OpenCode: Complete Loop Configuration',
        primaryKeyword: 'playwright agents opencode',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-agent-trace-driven-repair-guide-2026',
        title: 'Trace-Driven Playwright Test Repair for Coding Agents',
        primaryKeyword: 'playwright agent trace repair',
        intent: 'troubleshooting',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'playwright-agent-test-governance-review-guide-2026',
        title: 'How to Review AI-Generated Playwright Tests Before Merge',
        primaryKeyword: 'review ai generated playwright tests',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
  {
    id: 'ai-test-automation',
    name: 'AI-Powered Test Automation',
    audience: 'QA teams applying AI to traditional software testing workflows',
    rationale:
      'Separate the intent of using AI to improve conventional QA from the different intent of evaluating LLM and agent products.',
    evidenceSources: [
      'https://playwright.dev/docs/test-agents',
      'https://istqb.org/certifications/certified-tester-ai-testing-ct-ai/',
      'https://istqb.org/istqb-releases-certified-tester-ai-testing-ct-ai-syllabus-version-2-0/',
      'https://genai.owasp.org/initiatives/agentic-security-initiative/',
    ],
    topics: [
      {
        slug: 'ai-test-automation-tools-2026',
        title: 'AI Test Automation Tools and Workflows for QA Teams in 2026',
        primaryKeyword: 'ai test automation tools',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'istqb-ct-ai-v2-guide-2026',
        title: 'ISTQB CT-AI v2.0 Guide for QA Engineers: What Changed in 2026',
        primaryKeyword: 'istqb ct-ai v2',
        intent: 'informational',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'ai4testing-vs-testing-ai-guide-2026',
        title: 'AI4Testing vs Testing AI: Two Different QA Strategies Explained',
        primaryKeyword: 'ai4testing vs testing ai',
        intent: 'comparison',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'testing-ai-generated-code-sdet-playbook',
        title: 'How to Test AI-Generated Code: A Practical SDET Review Playbook',
        primaryKeyword: 'testing ai generated code',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'self-healing-test-automation-guide',
        title: 'Self-Healing Test Automation Governance for Reliable QA Suites',
        primaryKeyword: 'self healing test automation',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'probabilistic-ai-system-testing-guide-2026',
        title: 'How to Test Probabilistic AI Systems with Non-Deterministic Outputs',
        primaryKeyword: 'testing probabilistic ai systems',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'metamorphic-testing-ai-llm-examples-2026',
        title: 'Metamorphic Testing Examples for Machine Learning and LLM Systems',
        primaryKeyword: 'metamorphic testing ai examples',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'ai-model-data-drift-testing-guide-2026',
        title: 'How to Test Data Drift and Model Drift in Production AI Systems',
        primaryKeyword: 'data drift model drift testing',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'ml-label-correctness-testing-guide-2026',
        title: 'Label Correctness Testing for ML Training and Evaluation Datasets',
        primaryKeyword: 'label correctness testing',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'ai-test-generation-human-review-guide-2026',
        title: 'Validate AI-Generated Test Cases Before Adding Them to Regression',
        primaryKeyword: 'validate ai generated test cases',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
  {
    id: 'llm-agent-testing',
    name: 'LLM and AI Agent Testing',
    audience: 'Engineers validating LLM applications, chatbots, and tool-using agents',
    rationale:
      'Create one framework-neutral evaluation foundation for datasets, judges, CI gates, agent behavior, non-determinism, cost, and multi-turn quality.',
    evidenceSources: [
      'https://developers.openai.com/api/docs/guides/evaluation-best-practices',
      'https://openai.com/index/introducing-agentkit/',
      'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents',
    ],
    topics: [
      {
        slug: 'testing-llm-applications-guide',
        title: 'LLM Testing Complete Guide: Evals, Agents, RAG, and Quality Gates',
        primaryKeyword: 'llm testing',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'openai-evals-platform-shutdown-migration-2026',
        title: 'OpenAI Evals Platform Shutdown: Migration Checklist for November 2026',
        primaryKeyword: 'openai evals shutdown migration',
        intent: 'troubleshooting',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'llm-eval-harness-production-guide-2026',
        title: 'How to Build an LLM Eval Harness That Matches Production Behavior',
        primaryKeyword: 'llm eval harness',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'deterministic-graders-vs-llm-judge-human-review-2026',
        title: 'Deterministic Graders vs LLM Judges vs Human Review',
        primaryKeyword: 'deterministic graders vs llm judge',
        intent: 'comparison',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'ai-agent-eval-testing-guide',
        title: 'AI Agent Evaluation Guide for Tools, Trajectories, and Task Success',
        primaryKeyword: 'ai agent evaluation',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'capability-vs-regression-evals-guide-2026',
        title: 'Capability Evals vs Regression Evals: When a Benchmark Should Graduate',
        primaryKeyword: 'capability evals vs regression evals',
        intent: 'comparison',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'pass-at-k-vs-pass-power-k-agent-reliability-2026',
        title: 'pass@k vs pass^k for Agent Reliability: Formula and Use Cases',
        primaryKeyword: 'pass@k vs pass^k',
        intent: 'informational',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'llm-judge-calibration-guide-2026',
        title: 'How to Calibrate an LLM Judge Against Expert Labels',
        primaryKeyword: 'llm judge calibration',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'grader-reward-hacking-evaluation-awareness-guide-2026',
        title: 'Detect Grader Hacking, Reward Hacking, and Evaluation Awareness',
        primaryKeyword: 'grader hacking llm evaluation',
        intent: 'security',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'production-traffic-llm-eval-dataset-guide-2026',
        title: 'How to Build an LLM Eval Dataset That Matches Production Traffic',
        primaryKeyword: 'production llm eval dataset',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
  {
    id: 'deepeval',
    name: 'DeepEval LLM Testing',
    audience: 'Python QA engineers adopting pytest-style LLM and agent evaluations',
    rationale:
      'DeepEval now spans 50+ metrics, tracing-based agent evaluation, RAG, synthetic data, conversations, and MCP systems, creating clear implementation searches.',
    evidenceSources: [
      'https://deepeval.com/docs/introduction',
      'https://deepeval.com/docs/getting-started-agents',
      'https://deepeval.com/docs/metrics-introduction',
    ],
    topics: [
      {
        slug: 'deepeval-llm-testing-guide',
        title: 'DeepEval 4 Tutorial for Pytest-Style LLM, RAG, and Agent Testing',
        primaryKeyword: 'deepeval 4 tutorial',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'deepeval-3-to-4-migration-guide-2026',
        title: 'DeepEval 3 to 4 Migration Guide for Traces and Multi-Turn Goldens',
        primaryKeyword: 'deepeval 4 migration',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'deepeval-skill-codex-claude-cursor-install-2026',
        title: 'How to Install the DeepEval Skill in Codex, Claude Code, and Cursor',
        primaryKeyword: 'deepeval skill install',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'deepeval-conversation-simulator-guide-2026',
        title: 'DeepEval ConversationSimulator Tutorial with Synthetic Users',
        primaryKeyword: 'deepeval conversation simulator',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'deepeval-task-completion-metric-agent',
        title: 'DeepEval TaskCompletionMetric: Trace Setup and Failure Analysis',
        primaryKeyword: 'deepeval task completion metric',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'deepeval-tool-correctness-metric-example',
        title: 'DeepEval ToolCorrectnessMetric for Arguments, Outputs, and Order',
        primaryKeyword: 'deepeval tool correctness metric',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'deepeval-simulation-graph-stopping-controller-2026',
        title: 'Build a DeepEval Simulation Graph with Stopping Controllers',
        primaryKeyword: 'deepeval simulation graph',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'deepeval-conversational-geval-rubric-guide-2026',
        title: 'Write Multi-Turn Rubrics with DeepEval Conversational G-Eval',
        primaryKeyword: 'deepeval conversational g eval',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'deepeval-generate-multiturn-goldens-cli-2026',
        title: 'Generate Single-Turn and Multi-Turn Goldens with the DeepEval CLI',
        primaryKeyword: 'deepeval generate goldens cli',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'deepeval-pytest-cicd-guide-2026',
        title: 'Run DeepEval with Pytest in CI/CD and Pull Request Quality Gates',
        primaryKeyword: 'deepeval pytest ci cd',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
  {
    id: 'promptfoo',
    name: 'Promptfoo Evaluation and Red Teaming',
    audience: 'JavaScript and platform teams testing prompts, RAG, agents, and MCP systems',
    rationale:
      'Promptfoo has current demand around eval matrices, 50+ vulnerability classes, RAG, MCP agent security, CI gates, graders, and its own MCP server.',
    evidenceSources: [
      'https://www.promptfoo.dev/docs/intro/',
      'https://openai.com/index/openai-to-acquire-promptfoo/',
      'https://www.promptfoo.dev/docs/integrations/agent-skill/',
      'https://www.promptfoo.dev/docs/providers/mcp/',
    ],
    topics: [
      {
        slug: 'promptfoo-complete-guide-2026',
        title: 'Promptfoo Complete Guide for LLM Evals, RAG, and Red Teaming',
        primaryKeyword: 'promptfoo',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'openai-promptfoo-acquisition-explained-2026',
        title: "What OpenAI's Promptfoo Acquisition Means for Open-Source LLM Testing",
        primaryKeyword: 'openai promptfoo acquisition',
        intent: 'informational',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'promptfoo-agent-skills-codex-claude-install-2026',
        title: 'Install Promptfoo Agent Skills in Codex and Claude Code',
        primaryKeyword: 'promptfoo agent skills',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'promptfoo-mcp-provider-security-testing-2026',
        title: "Test and Red-Team an MCP Server with Promptfoo's MCP Provider",
        primaryKeyword: 'promptfoo mcp provider',
        intent: 'security',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'promptfoo-evaluate-codex-vs-claude-agents-2026',
        title: 'Evaluate Codex vs Claude Coding Agents with Promptfoo',
        primaryKeyword: 'promptfoo coding agent evaluation',
        intent: 'comparison',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'promptfoo-mcp-server-integration-guide-2026',
        title: 'Run Promptfoo as an MCP Server for Agent-Driven Evals',
        primaryKeyword: 'promptfoo mcp server',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'promptfoo-cicd-evaluation-gates-guide-2026',
        title: 'Promptfoo CI Gates with GitHub Actions, JUnit XML, and Run Tags',
        primaryKeyword: 'promptfoo github actions ci',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'promptfoo-deterministic-assertions-vs-llm-rubric-2026',
        title: 'Promptfoo Deterministic Assertions vs llm-rubric Graders',
        primaryKeyword: 'promptfoo assertions vs llm rubric',
        intent: 'comparison',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'promptfoo-rag-document-poisoning-redteam-2026',
        title: 'Poison RAG Documents with promptfoo redteam for Security Testing',
        primaryKeyword: 'promptfoo rag document poisoning',
        intent: 'security',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'promptfoo-provider-auth-timeout-debugging-2026',
        title: 'Debug Promptfoo Target Authentication, Timeouts, and Input Mappings',
        primaryKeyword: 'promptfoo provider debugging',
        intent: 'troubleshooting',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
  {
    id: 'rag-testing',
    name: 'RAG Testing and Evaluation',
    audience: 'QA and ML engineers validating retrieval-augmented generation systems',
    rationale:
      'Tool-neutral RAG testing needs a canonical foundation across retrieval, generation, synthetic datasets, security, chunking, reranking, citation, and abstention.',
    evidenceSources: [
      'https://docs.ragas.io/en/stable/concepts/metrics/available_metrics/',
      'https://docs.ragas.io/en/stable/concepts/test_data_generation/',
      'https://www.promptfoo.dev/docs/guides/evaluate-rag/',
    ],
    topics: [
      {
        slug: 'rag-evaluation-metrics-complete-2026',
        title: 'RAG QA Testing Guide for Retrieval, Generation, and Citation Quality',
        primaryKeyword: 'rag testing',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'rag-retrieval-vs-generation-failure-diagnosis-2026',
        title: 'How to Tell Whether a RAG Failure Comes from Retrieval or Generation',
        primaryKeyword: 'rag retrieval vs generation failure',
        intent: 'troubleshooting',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'rag-context-precision-recall-guide-2026',
        title: 'Contextual Precision vs Recall vs Relevancy for RAG Testing',
        primaryKeyword: 'rag context precision recall relevancy',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'rag-high-relevance-low-faithfulness-diagnosis-2026',
        title: 'High Answer Relevance but Low Faithfulness: Diagnose Wrong RAG Answers',
        primaryKeyword: 'high relevance low faithfulness rag',
        intent: 'troubleshooting',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'rag-synthetic-testset-generation-ragas-guide-2026',
        title: 'Generate Synthetic RAG Testsets with Ragas and Your Documents',
        primaryKeyword: 'rag synthetic testset generation',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'rag-source-aware-context-precision-guide-2026',
        title: 'Source-Aware Context Precision for Retrieved Documents and Chunks',
        primaryKeyword: 'source aware context precision rag',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'rag-vector-database-comparison-eval-dataset-2026',
        title: 'Compare Vector Databases with One Fixed RAG Evaluation Dataset',
        primaryKeyword: 'compare vector databases rag evaluation',
        intent: 'comparison',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'testing-rag-no-answer-abstention',
        title: 'Test RAG No-Answer and Abstention Behavior When Context Is Missing',
        primaryKeyword: 'rag no answer abstention testing',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'cross-lingual-rag-evaluation-guide-2026',
        title: 'Cross-Lingual RAG Evaluation for Multilingual Queries and Documents',
        primaryKeyword: 'cross lingual rag evaluation',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'multi-turn-rag-evaluation-guide-2026',
        title: 'Multi-Turn RAG Evaluation for Conversational Assistants',
        primaryKeyword: 'multi turn rag evaluation',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
  {
    id: 'mcp-testing',
    name: 'MCP Server Testing and Security',
    audience: 'QA, platform, and security engineers shipping Model Context Protocol servers',
    rationale:
      'MCP testing has distinct protocol, Inspector, contract, security, CI, task, elicitation, OAuth, compatibility, and reliability searches with growing 2026 relevance.',
    evidenceSources: [
      'https://github.com/modelcontextprotocol/conformance',
      'https://modelcontextprotocol.io/docs/tools/inspector',
      'https://modelcontextprotocol.io/specification/2025-11-25/changelog',
      'https://modelcontextprotocol.io/docs/tutorials/security/security_best_practices',
      'https://genai.owasp.org/initiatives/agentic-security-initiative/',
    ],
    topics: [
      {
        slug: 'mcp-server-testing-guide-2026',
        title: 'MCP Server Testing Complete Guide for Protocol, Tools, and Security',
        primaryKeyword: 'mcp server testing',
        intent: 'informational',
        role: 'pillar',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'mcp-official-conformance-suite-server-guide-2026',
        title: 'Run the Official MCP Conformance Suite Against Your Server',
        primaryKeyword: 'mcp conformance suite server',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'mcp-conformance-github-actions-baseline-2026',
        title: 'Add MCP Conformance Tests to GitHub Actions with Failure Baselines',
        primaryKeyword: 'mcp conformance github actions',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'new',
      },
      {
        slug: 'mcp-inspector-tutorial-2026',
        title: 'Use MCP Inspector CLI to Automate tools/list and tools/call Tests',
        primaryKeyword: 'mcp inspector cli testing',
        intent: 'tutorial',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'mcp-server-contract-testing-guide',
        title: 'Test MCP Tool Schemas, Defaults, Invalid Inputs, and Error Types',
        primaryKeyword: 'mcp tool schema contract testing',
        intent: 'implementation',
        role: 'child',
        publicationWave: 1,
        canonicalStrategy: 'upgrade',
      },
      {
        slug: 'mcp-client-auth-metadata-conformance-2026',
        title: 'Test an MCP Client with Authorization and Metadata Conformance',
        primaryKeyword: 'mcp client auth conformance testing',
        intent: 'implementation',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'mcp-stdio-vs-streamable-http-testing-2026',
        title: 'How to Test MCP stdio vs Streamable HTTP Transports',
        primaryKeyword: 'mcp stdio vs streamable http testing',
        intent: 'comparison',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'mcp-oauth-confused-deputy-token-passthrough-tests-2026',
        title: 'MCP OAuth Tests for Confused Deputy and Token Passthrough Attacks',
        primaryKeyword: 'mcp oauth security testing',
        intent: 'security',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'mcp-ssrf-metadata-redirect-testing-2026',
        title: 'MCP SSRF Test Cases for Metadata Discovery and Redirect Chains',
        primaryKeyword: 'mcp ssrf testing',
        intent: 'security',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
      {
        slug: 'mcp-session-hijacking-stateful-stream-tests-2026',
        title: 'MCP Session Hijacking Tests for Stateful and Resumable Streams',
        primaryKeyword: 'mcp session hijacking testing',
        intent: 'security',
        role: 'child',
        publicationWave: 2,
        canonicalStrategy: 'new',
      },
    ],
  },
];

export const SEO_WAVE_LAUNCH_DATE_2026 = '2026-07-14';

export const seoUpgradeOriginalPublicationDates2026 = {
  'playwright-e2e-complete-guide': '2026-02-13',
  'playwright-locators-best-practices-2026': '2026-04-01',
  'playwright-browser-context-guide-2026': '2026-04-01',
  'playwright-starthar-tracing-guide': '2026-07-13',
  'playwright-drop-api-drag-and-drop': '2026-07-13',
  'playwright-cli-complete-guide-2026': '2026-03-24',
  'playwright-mcp-browser-automation-guide': '2026-05-18',
  'playwright-mcp-json-configuration-reference': '2026-06-03',
  'playwright-mcp-security-best-practices-2026': '2026-03-24',
  'playwright-mcp-docker-guide-2026': '2026-03-24',
  'playwright-test-agents-planner-generator-healer': '2026-07-03',
  'playwright-init-agents-guide': '2026-07-06',
  'playwright-healer-agent-self-healing-tests': '2026-07-07',
  'ai-test-automation-tools-2026': '2026-02-17',
  'testing-ai-generated-code-sdet-playbook': '2026-02-19',
  'self-healing-test-automation-guide': '2026-07-02',
  'testing-llm-applications-guide': '2026-03-17',
  'ai-agent-eval-testing-guide': '2026-04-13',
  'llm-judge-calibration-guide-2026': '2026-07-09',
  'deepeval-llm-testing-guide': '2026-07-05',
  'deepeval-task-completion-metric-agent': '2026-07-13',
  'deepeval-tool-correctness-metric-example': '2026-07-13',
  'promptfoo-complete-guide-2026': '2026-05-21',
  'rag-evaluation-metrics-complete-2026': '2026-06-04',
  'rag-context-precision-recall-guide-2026': '2026-03-24',
  'testing-rag-no-answer-abstention': '2026-07-13',
  'mcp-server-testing-guide-2026': '2026-06-14',
  'mcp-inspector-tutorial-2026': '2026-03-24',
  'mcp-server-contract-testing-guide': '2026-07-10',
} as const;

export function getSeoTopicPublicationDate2026(topic: SeoTopicPlanItem): string {
  if (topic.canonicalStrategy === 'new') return SEO_WAVE_LAUNCH_DATE_2026;

  const originalDate =
    seoUpgradeOriginalPublicationDates2026[
      topic.slug as keyof typeof seoUpgradeOriginalPublicationDates2026
    ];

  if (!originalDate) throw new Error(`Missing original publication date for ${topic.slug}`);
  return originalDate;
}

export const seoTopicPlan2026 = seoTopicClusters2026.flatMap((cluster) =>
  cluster.topics.map((topic) => ({ ...topic, clusterId: cluster.id })),
);

export const seoPublicationWaveOne2026 = seoTopicPlan2026.filter(
  (topic) => topic.publicationWave === 1,
);
